azs:
- name: z1

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    disk: 10240
    ram: 2048
- name: concourse-web
  cloud_properties:
    cpu: 2
    disk: 50000
    nested_hardware_virtualization: true
    ram: 8192
- name: concourse-db
  cloud_properties:
    cpu: 4
    disk: 10240
    nested_hardware_virtualization: true
    ram: 8192
- name: concourse-workers
  cloud_properties:
    cpu: 2
    disk: 300000
    nested_hardware_virtualization: true
    ram: 8192

disk_types:
- name: default
  disk_size: 10240
  cloud_properties: { type: thin }
- name: provisioner
  disk_size: 10240
  cloud_properties: { type: thin }
- name: concourse-db
  disk_size: 200000
  cloud_properties: { type: thin }

networks:
- name: concourse 
  subnets:
  - az: z1
    cloud_properties:
      name: VM Network
    dns:
    - 8.8.8.8
    gateway: 10.0.0.1
    range: 10.0.0.1/24
    reserved:
    - 10.0.0.0 - 10.0.0.210
    - 10.0.0.221 - 10.0.0.255
    static:
    - 10.0.0.212 # concourse web
    - 10.0.0.213 # concourse db
 
  type: manual

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: default
  network: concourse
